version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres111:joobahomeassignment@db:5432/jooba_db
    networks:
      - jooba_network
    volumes:
      - ./backend:/backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - jooba_network
    volumes:
      - ./frontend:/frontend

  db:
    image: postgres:15
    container_name: jooba
    restart: always
    environment:
      POSTGRES_USER: postgres111
      POSTGRES_PASSWORD: joobahomeassignment
      POSTGRES_DB: jooba_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jooba_network

volumes:
  postgres_data:

networks:
  jooba_network:
    driver: bridge
